### ISSUE TITLE
Error R15 (Memory quota vastly exceeded)

### ISSUE THREAD

**Issue by AliAryanTech** [LuckyYam/WhatsApp-bot#10]
![Error](https://user-images.githubusercontent.com/85696485/174438280-3d492010-400b-4ca2-beab-7f20b1928c00.jpg)

**When gonna fix this problem**

**Comment by LuckyYam** [comment]
This is a Heroku problem, you can check it [here](https://devcenter.heroku.com/articles/node-memory-use).

**Comment by AliAryanTech** [comment]
> This is a Heroku problem, you can check it [here](https://devcenter.heroku.com/articles/node-memory-use).

**Then make it railway deplyable**
