### ISSUE TITLE
pm2 not found error 

### ISSUE THREAD

**Issue by AliAryanTech** [LuckyYam/WhatsApp-bot#14]
pm2 start dist/bot.js --node-args="--max-old-space-size=4096" && pm2 save && pm2 logs bot
app[web.1]: /bin/sh: 1: pm2: not found
app[web.1]: error Command failed with exit code 127.
app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Issa2001** [comment]
Why bot not working in 500+ members groups?

**Comment by AliAryanTech** [comment]
app[web.1]: yarn pm2 start dist/bot.js && yarn pm2 save && yarn pm2 logs bot
app[web.1]: error Command "pm2" not found.

**Comment by AliAryanTech** [comment]
> app[web.1]: yarn pm2 start dist/bot.js && yarn pm2 save && yarn pm2 logs bot app[web.1]: error Command "pm2" not found.

@LuckyYam
