### ISSUE TITLE
Still pm2 not found 

### ISSUE THREAD

**Issue by AliAryanTech** [LuckyYam/WhatsApp-bot#15]
app[web.1]: yarn pm2 start dist/bot.js && yarn pm2 save && yarn pm2 logs bot
app[web.1]: error Command "pm2" not found.

**Comment by LuckyYam** [comment]
I have dropped starting via `pm2`. If you still want to run via pm2 then add [pm2 buildpack](https://github.com/ItsJimi/heroku-buildpack-pm2) in your app and edit the Procfile or the `yarn start` command.
