### ISSUE TITLE
Mongoose error!

### ISSUE THREAD

**Issue by Issa2001** [LuckyYam/WhatsApp-bot#22]

**Comment by AliAryanTech** [comment]
> _No description provided._

Show error!?

**Comment by Issa2001** [comment]
![IMG_20220910_102214.jpg](https://user-images.githubusercontent.com/89695452/189473644-6dffe014-c503-40e0-b9e1-36e71f7d16d6.jpg)

**Comment by Issa2001** [comment]
Updated mongo from 6.4 to 6.5 also @typegoose, tried even new mongo url but same error... @AliAryanTech @LuckyYam

**Comment by AliAryanTech** [comment]
> Updated mongo from 6.4 to 6.5 also @typegoose, tried even new mongo url but same error... @AliAryanTech @LuckyYam

Why did you even update? 
Btw, I updated MongoDB module to mongoose@^6.5.0 and get no error
I guess, it's because of typegoose module so just undo that

**Comment by AliAryanTech** [comment]
Your problem fixed? @Issa2001

**Comment by Issa2001** [comment]
Not yet bro

**Comment by AliAryanTech** [comment]
> Not yet bro

Show full logs
